---
title: "Plot SDM predictions"
author: "steppe"
date: "4/7/2022"
output: pdf_document
---

```{r}
library(tidyverse)
library(raster)
library(here)
```


```{r import datasets for comparing rasters - was bored so played around with this code, message = F}
files <- list.files(paste0(here(), '/results/maps'), pattern = "tif$")

linear = files[str_detect(files, 'glm')]
machine = files[str_detect(files, 'ml')]

ls <- list('linear' = linear,  'machine' = machine) 
# so we can rerun this simply  as we tack on more species we will
# create two equal length vectors for binding into a dataframe
ls1 <- lengths(ls)
length( # here we pad the shorted list with NA's
  ls[[
    names(ls[which.min(ls1)])
    ]]
  ) <- max(ls1)

ls <- lapply(ls, data.frame) 
ls <- bind_cols(ls)
colnames(ls) <- c('linear', 'machine')

ls <- ls %>% 
  mutate(across(.cols = everything(), # create just a copy of the binomials
                  .fns = list(binomial = ~ gsub("_ml_2022.*|_glm_2022.*|", "", .)),
                  .names = "{fn}_{col}")
         ) %>% 
  mutate(across(!contains('binomial'),
         ~ paste0(here(), '/results/maps/', .x)
         ))

# now ensure that the data are in the same order as each other...
ls_mach <- ls %>% dplyr::select(contains('machine')) %>% drop_na()
ls_line <- ls %>% dplyr::select(contains('linear'))

# full here but may not end up being best option - inner may end up being best
rasters <- full_join(ls_line, ls_mach,
                     by = c("binomial_linear" =  "binomial_machine")
                     ) %>% 
  drop_na()

rl <- rasters %>% dplyr::select(linear, binomial_linear) %>% 
  distinct(linear, .keep_all = T)
rm <- rasters %>% dplyr::select(machine, binomial_linear) %>% 
  distinct(machine, .keep_all = T)
# HERE WILL DEAL WITH DROPPING NA' ACROSS ALL GROUPS

linear_stack <- terra::rast(rl$linear)
machine_stack <- terra::rast(rm$machine)

rm(ls, ls_mach, ls_line, linear, machine, files, ls1, rasters, rl, rm)
```

```{r Create composite rasters for visualization}

# due to a limitiation in the C implementation I had to run these by hand... even though
# my computer was able to do do it on all 594 datasets at once... (i did not save the results)
#lin_mean <- terra::app(linear_stack[[496:594]], 
#                       filename = paste0(here(), '/results/plots/', 
#                                         'linear_model_mean5.tif'),
#                                         fun = 'mean', overwrite = T)

files <- paste0(here(),'/results/plots/', list.files(paste0(here(), '/results/plots'), pattern = "tif$"))
linear = files[str_detect(files, 'linear')]
linear_stack <- terra::rast(linear)
mean_linear <- mean(linear_stack)

#mach_mean <- terra::app(machine_stack[[446:534]],
#                        filename = paste0(here(), '/results/plots/', 
#                                          'machine_model_mean5.tif'),
#                        fun = 'mean', 
#                        overwrite = F)

files <- paste0(here(),'/results/plots/', list.files(paste0(here(), '/results/plots'), pattern = "tif$"))
machine = files[str_detect(files, 'machine')]
machine_stack <- terra::rast(machine)
mean_machine <- mean(machine_stack)
plot(mean_machine)
plot(mean_linear)

mean_variances <- mean_linear - mean_machine
# either way determine the absolute differences in mean predictions
plot(mean_variances)

rm(files, machine, machine_stack, linear_stack)
```

